version: '3.8'

services:
  api:
    build: image-categorizer
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./image-categorizer:/app
      - /app/node_modules
    command: npm run dev

summarizer:
  build: ./summarizer
  ports:
    - "3002:3001"  # HTTP para acesso pelo host
    - "5000:5000"  # expõe a porta MCP do container para o host (essencial!)
  environment:
    - NODE_ENV=development
    - PORT=3001
    - MCP_PORT=5000
    - OPENROUTER_API_URL=https://openrouter.ai/image-categorizer/v1/chat/completions
    - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
  volumes:
    - ./summarizer:/app
    - /app/node_modules
  command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_SUMMARIZER_URL=http://localhost:3002
    depends_on:
      - api
      - summarizer

networks:
  default:
    driver: bridge
